### ISSUE TITLE
Regular admins - User dropdown - Menu spacing weirdness

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#47]
refer to space beneath user management

**Comment by austintruchan** [comment]
<img width="303" alt="screen shot 2018-05-03 at 1 12 01 pm" src="https://user-images.githubusercontent.com/5408529/39592029-96e6d0a0-4ed3-11e8-8be9-fbe5de02c434.png">

**Comment by suuuth** [comment]
adjusted `right` value for `.navigation-sub-menu` in `_right.scss` found at `resources/assets/scss/partials/navigation/_right.scss`

**Comment by suuuth** [comment]
Okay it should be fixed now.  The issue was the `nav` had a width of `100vw`, which caused the right edge to be cut off by the vertical page-body scroll bar when this scroll bar was present.  This was also causing the dropdowns on the right edge to be cut off.  Changing this width value from `100vw` to `100%` seems to prevent the vertical scroll bar from cutting off any of the nav, including nav-submenus.

**Comment by austintruchan** [comment]
Hmmm. Still seeing User Management be too close to the line above logout though.

**Comment by austintruchan** [comment]
I remember you had this working at one point, and I approved. So I approve.

**Comment by suuuth** [comment]
the fix for this was pulled from pull request #135 and can be seen [here](https://github.com/matrix-msu/Kora3/pull/135/commits/49c9d348c6544183576f53437a0edfa810d11683) in the file `resources/assets/scss/partials/_navigation.scss`
